title: My Typography Blog
description: A website for my blogs
header_text: Typography On The Big Screen
footer_text: Copyright 2020 Charlotte Pollard
header_feature_image: ../uploads/cinema-un.jpg
bannerheight: 100vh
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
