title: My Typography Blog
description: A website for my blogs
header_text: Typography On The Big Screen
footer_text: Copyright 2020 Charlotte Rose Pollard
header_feature_image: ../uploads/cinema-1.jpg
bannerheight: 20vmax
logo: ../uploads/logo.png
favicon: ../uploads/fabi-pic.jpg
gridlayout: true
fixednavbar: false
upzoom: true
